enum ActionTypes {
  REQUEST_CREATE_POST = 'post/REQUEST_CREATE_POST',
  REQUEST_CREATE_POST_SUCCESS = 'post/REQUEST_CREATE_POST_SUCCESS',
  REQUEST_CREATE_POST_ERROR = 'post/REQUEST_CREATE_POST_ERROR',
}

export default ActionTypes
