enum ActionTypes {
  REQUEST_GET_USER_INFO = 'user/REQUEST_GET_USER_INFO',
  REQUEST_GET_USER_INFO_SUCCESS = 'user/REQUEST_GET_USER_INFO_SUCCESS',
  REQUEST_GET_USER_INFO_ERROR = 'user/REQUEST_GET_USER_INFO_ERROR',

  REQUEST_SIGN_UP = 'user/REQUEST_SIGN_UP',
  REQUEST_SIGN_UP_SUCCESS = 'user/REQUEST_SIGN_UP_SUCCESS',
  REQUEST_SIGN_UP_ERROR = 'user/REQUEST_SIGN_UP_ERROR',

  REQUEST_EDIT_USER_INFO = 'user/REQUEST_EDIT_USER_INFO',
  REQUEST_EDIT_USER_INFO_SUCCESS = 'user/REQUEST_EDIT_USER_INFO_SUCCESS',
  REQUEST_EDIT_USER_INFO_ERROR = 'user/REQUEST_EDIT_USER_INFO_ERROR',

  REQUEST_SIGN_IN = 'user/REQUEST_SIGN_IN',
  REQUEST_SIGN_IN_SUCCESS = 'user/REQUEST_SIGN_IN_SUCCESS',
  REQUEST_SIGN_IN_ERROR = 'user/REQUEST_SIGN_IN_ERROR',

  REQUEST_LOGOUT = 'user/REQUEST_LOGOUT',
  REQUEST_LOGOUT_SUCCESS = 'user/REQUEST_LOGOUT_SUCCESS',
  REQUEST_LOGOUT_ERROR = 'user/REQUEST_LOGOUT_ERROR',
}

export default ActionTypes
